<table>
    <thead>
        <tr>
            <th>Make</th>
            <th>Model</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
